name = "twitter-rss"
main = "src/index.js"
compatibility_date = "2025-10-08"

# your existing KV ids here
kv_namespaces = [
  { binding = "FEEDS", id = "9006b0c504c446b783dfbf1a57b4d3f3", preview_id = "660075074f114308a05a5c0c9d844753" },
  { binding = "META",  id = "22b6fd7827884b0b81cfd6371727b611",  preview_id = "22839b4beb3c479391ae49581e02a931"  }
]

[triggers]
crons = ["0 */3 * * *"]   # every 3 hours

# map the worker to a subdomain on your Cloudflare zone
routes = [
  { pattern = "https://feeds.sammii.dev/*", custom_domain = true }
]

# optional: use edge resources during dev
[dev]
remote = true
